version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studdb
    ports:
      - "5432:5432"
    networks:
      - net1

  loadbalancer:
    build: ./load_balancer
    container_name: loadbalancer
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studdb
    ports:
      - "8000:8000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net1

networks:
  net1:
    driver: bridge
    name: net1
